### ISSUE TITLE
Forms 3.0 - Minversion 25 - Todo

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1328]
- [x] Bump @nextcloud/vue to v7 #1338 
- [x] Check breaking changes of vue-7
- [x] Set Minversion 25 #1348 
- [x] Test migration from NC24 with Forms 2.5.1 to NC25 with Forms 3.0
- [x] Change Icons for Link and Results #1344 
- [x] Switch public link and internal link in sharing tab #1344
- [x] Fix alignment of textboxes in Edit/Create mode to reduce jumping of text #1322 
- [x] Move Checkboxes/Radios to NcCheckboxRadioSwitch #1322 
- [x] Remove obsolete css #1352 
- [x] Align "Add question" button #1351 
- [x] Fix results bar #1356 
- [x] Fix upgrade error #1361 
- [x] Fix actions container #1359 
- [x] Fix moving of text in Edit mode #1362 
- [x] Adjust date/time picker height #1363
- [x] Fix public view #1365 
- [x] Adjust long text questions #1364  
- [x] Bump @nextcloud/vue to final v7 when released #1377
