### ISSUE TITLE
V2 - Bugs

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#261]
- [x] The active class on the navigation is cleared when you are in the response view, but should keep having the relevant form highlighted as active. #379
- [x] Fastly changing forms a few times, somwhen runs into an error, that overwrites one form with another one, and logs `TypeError: "this.form.form is undefined"` on console #393 
- [x] When deleting a form, the Main-Content (editing Form) is not updated. #377
- [x] When within a result-view and selecting another result-view from sidebar, the Result-Content is not updated. #377
- [x] On mobile, the navigation doesn’t close when you click on a form or create new #380
- [x] The title is just "Forms - Nextcloud" but should be "Form name - Forms - Nextcloud" so you can see the relevant part even when the tab is short. Same for share view #368 
- [x] The actions menu has the form name as a title for every action, leading to it showing when you hover over the action → not necessary and actually confusing, also for accessibility? https://github.com/nextcloud/nextcloud-vue/pull/1098
- [x] When fastly deleting answers by keyboard, a few answers get deleted, then the backspace suddenly applies to the browser, therefore switching pages #394 

- [ ] Find a way to merge the two layouts base for both views (they use the same styling for header and form/section) #400 
- [x] When emptying an answer and leaving the edit mode, it remove the empty one (on purpose) but not removed from the database #388  https://github.com/nextcloud/forms/blob/ee65ef7d2d3ce3c679919e5326e8224468e04e3e/src/components/Questions/QuestionMultiple.vue#L128
- [x] Shares are not shown, when opening the edit-mode for the first time
- [x] Add extra padding at the bottom like in creation mode https://github.com/nextcloud/forms/blob/dd06c4671cfcb3377e50e38d430b633944d0f1d0/src/views/Create.vue#L421
- [x] When a form has an expirationDate, this date is not shown when editing the form (in a later session than when it was created, expirationDate not shown/loaded from Db).
- [x] When switching forms, you always get "Formname successfully saved" as notification. This is not really necessary and has to be clicked away always.
- [x] Impossible to close the sidebar at the moment?
- [x] The menu icon overlaps the first line of text
- [x] There is a vertical scrollbar even when there’s almost no content. Seems to be cause there’s some extra whitespace to the top above the content and sidebar
- [x] Form description and questions should be below each other, not side by side
- [x] The content has some different font sizes, especially e.g. for questions. This looks quite off. Instead the questions could be bold to emphasize.
- [x] All the settings in the sidebar are bold, taking away focus and making everything look the same

**Comment by jotoeri** [comment]
By @jancborchardt at Cleanup/Change-Routes-PR

- [ ] When switching forms, you always get "Formname successfully saved" as notification. This is not really necessary and has to be clicked away always.
- [ ] The actions menu has the form name as a title for every action, leading to it showing when you hover over the action → not necessary and actually confusing, also for accessibility?
- [ ] Impossible to close the sidebar at the moment?
- [ ] On mobile, the navigation doesn’t close anymore after you open it once
- [ ] The menu icon overlaps the first line of text
- [ ] There is a vertical scrollbar even when there’s almost no content. Seems to be cause there’s some extra whitespace to the top above the content and sidebar:
   ![forms whitespace](https://user-images.githubusercontent.com/925062/77411642-05191d80-6dbd-11ea-9dee-fbbf7d9dd245.png)


Possibly for a different pull request (if so please put them in an issue so it doesn’t get lost):
- [ ] The title is "Forms - Form name" but should be "Form name - Forms" so you can see the relevant part even when the tab is short.
- [ ] Form description and questions should be below each other, not side by side
- [ ] The content has some different font sizes, especially e.g. for questions. This looks quite off. Instead the questions could be bold to emphasize.
- [ ] All the settings in the sidebar are bold, taking away focus and making everything look the same

**Comment by jotoeri** [comment]
From [this comment](https://github.com/nextcloud/forms/issues/229#issuecomment-601908185).

- [ ] Allow only one submission per user should be enabled for only-shared access, as it is a subset of only registered users.
- [ ] Voting onto an expired form just shows Access-Denied to user. Some Expired-Notification would be better.

**Comment by jotoeri** [comment]
- [ ] Fastly changing forms a few times, somwhen runs into an error, that overwrites one form with another one, and logs `TypeError: "this.form.form is undefined"` on console
- [ ] Shares are not shown, when opening the edit-mode for the first time

**Comment by skjnldsv** [comment]
- [ ] Add extra padding at the bottom like in creation mode https://github.com/nextcloud/forms/blob/dd06c4671cfcb3377e50e38d430b633944d0f1d0/src/views/Create.vue#L421
- [ ] Find a way to merge the two layouts base for both views (they use the same styling for header and form/section)
- [ ] When emptying an answer and leaving the edit mode, it remove the empty one (on purpose) but not removed from the database https://github.com/nextcloud/forms/blob/ee65ef7d2d3ce3c679919e5326e8224468e04e3e/src/components/Questions/QuestionMultiple.vue#L128

**Comment by jancborchardt** [comment]
Best add the points only to the original post above, and double-check if they are fixed or not (just did that for my block of comments. :)

**Comment by jancborchardt** [comment]
@skjnldsv @jotoeri I did the ones I could do, none of the remaining items are in my area of expertise anymore. You can take this over, and I’ll move on to the **Design review of current state #296** list (where your JS help is also needed ;)

cc @nextcloud/forms if anyone wants to help!

**Comment by jancborchardt** [comment]
Very nice! Only one missing is

> Find a way to merge the two layouts base for both views (they use the same styling for header and form/section)

Is this still relevant, and maybe then we should open a separate issue for that so we can close this collection? And then we can continue on to fixing the rest of **Design review of current state #296** :)

**Comment by jotoeri** [comment]
> Is this still relevant, and maybe then we should open a separate issue for that so we can close this collection?

Sounds useful, yes 👍 It's more a code-thing, that imo could also be scheduled for V2.1.

**Comment by jancborchardt** [comment]
@jotoeri do you want to open a new issue for that, I think you can probably write that down better as I have very little code knowledge. ;)
